PROJECT=jdksavdecc-proxy
PROJECT_NAME=jdksavdecc-proxy
PROJECT_VERSION?=201304286
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=ISC
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2013
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=https://avb.statusbar.com/jdksavdecc-proxy
PROJECT_IDENTIFIER=org.statusbar.jdksavdecc-proxy
TOP_LIB_DIRS+=.
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

CONFIG_TOOLS=

