PROJECT=jdksavdecc-proxy
PROJECT_NAME=jdksavdecc-proxy
PROJECT_VERSION?=20140109
PROJECT_EMAIL=jeffk@jdkoftinoff.com
PROJECT_LICENSE=ISC
PROJECT_MAINTAINER=jeffk@jdkoftinoff.com
PROJECT_COPYRIGHT=Copyright 2014
PROJECT_DESCRIPTION=
PROJECT_WEBSITE=http://avb.statusbar.com/page/code/jdksavdecc-proxy/
PROJECT_IDENTIFIER=com.statusbar.jdksavdecc-proxy
TOP_LIB_DIRS+=. microsupport jdksavdecc-c
CONFIG_TOOLS+=
PKGCONFIG_PACKAGES+=
TEST_OUT_SUFFIX=txt

DEFINES+=US_ENABLE_RAW_ETHERNET=1

ifeq ($(TARGET_PLATFORM_LINUX),1)
DEFINES+=US_ENABLE_SYSLOG=1
endif

ifeq ($(TARGET_PLATFORM_MACOSX),1)
DEFINES+=US_ENABLE_SYSLOG=1
DEFINES+=US_ENABLE_PCAP=1
LDLIBS+=-lpcap
endif


